export const PRODUCTS = [
  {
    "name": "Playera NY Herald Tribune",
    "description": "Playera de algodón premium con el diseño icónico de la prensa neoyorquina. Estilo minimalista que destaca por su tipografía clásica en contraste negro sobre fondo blanco. Una prenda atemporal, cómoda y fácil de combinar.\n\nDiseño: Serigrafía/Impresión de alta definición para letras nítidas.\n\nEstilo: Vintage / Urbano.\n\nCorte: Clásico unisex.",
    "price": "150",
    "category": "HOMBRE",
    "type": "PLAYERA",
    "theme": "VINTAGE",
    "hasSizes": true,
    "specialLabel": "Ninguna",
    "id": 1,
    "imageType": "SÓLO FRENTE",
    "frenteImage": "https://i.postimg.cc/C59NXsxM/Playera_de_Herald.jpg",
    "reversaImage": ""
  },
  {
    "name": "Playera NY Herald Tribune",
    "description": "\"Playera de algodón premium con el diseño icónico de la prensa neoyorquina. Estilo minimalista que destaca por su tipografía clásica en contraste negro sobre fondo blanco. Una prenda atemporal, cómoda y fácil de combinar.\n\nDiseño: Serigrafía/Impresión de alta definición para letras nítidas.\n\nEstilo: Vintage / Urbano.\n\nCorte: Clásico unisex.\"\n",
    "price": "150",
    "category": "MUJER",
    "type": "PLAYERA",
    "theme": "VINTAGE",
    "hasSizes": true,
    "specialLabel": "Ninguna",
    "id": 2,
    "imageType": "SÓLO FRENTE",
    "frenteImage": "https://i.postimg.cc/C59NXsxM/Playera_de_Herald.jpg",
    "reversaImage": ""
  },
  {
    "name": "María Félix - Época de Oro",
    "description": "\"Playera premium que rinde homenaje a la máxima leyenda del cine mexicano. Presenta un diseño artístico de María Félix con un acabado de alto contraste que resalta su mirada icónica y elegancia atemporal. Una prenda esencial para coleccionistas y amantes de la cultura cinematográfica de México.\n\nDiseño: Impresión de alta definición con detalle en rasgos y texturas.\n\nEstilo: Cine Mexicano / Vintage.\n\nCorte: Clásico unisex en algodón suave de alta durabilidad.\"\n",
    "price": "150",
    "category": "MUJER",
    "type": "playera",
    "theme": "cine mexicano",
    "hasSizes": true,
    "specialLabel": "Ninguna",
    "id": 3,
    "imageType": "SÓLO FRENTE",
    "frenteImage": "https://i.postimg.cc/nrNkgGhc/playera_maria_feliz.jpg",
    "reversaImage": ""
  },
  {
    "name": "You Never Walk Alone",
    "description": "\"Sudadera premium con el diseño emblemático de la era \"\"You Never Walk Alone\"\" de BTS. Presenta el icónico logotipo de las alas en contraste sobre el pecho y los nombres de los integrantes en la espalda. Una prenda de colección diseñada para brindar comodidad y estilo a los verdaderos fans de Bangtan.\n\nDiseño: Estampado de alta durabilidad con tipografía nítida y logotipos oficiales.\n\nEstilo: K-Pop / Streetwear Juvenil.\n\nAjuste: Confortable con capucha, cordones y bolsillo frontal tipo canguro.\"\n",
    "price": "450",
    "category": "MUJER",
    "type": "Sudaderas",
    "theme": "bts",
    "hasSizes": true,
    "specialLabel": "Ninguna",
    "id": 4,
    "imageType": "FRENTE Y REVERSA",
    "frenteImage": "https://i.postimg.cc/Gt4KX5d9/BTS_YNWL_FRENTE.png",
    "reversaImage": "https://i.postimg.cc/wM12wGgv/BTS_YNWL_REVERSO.png"
  },
  {
    "name": "\"Carrie\" – Edición Terror Clásico",
    "description": "\"Sudadera premium en color negro profundo con diseño gráfico de la icónica película de Stephen King. Presenta el rostro de Carrie White en un contraste de alto impacto visual, capturando la esencia del suspenso y el cine de culto. Una prenda cómoda y duradera para fanáticos del género horror.\n\nDiseño: Estampado de gran detalle con enfoque en el dramatismo visual.\n\nEstilo: Cine de Terror / Culto.\n\nAjuste: Corte cómodo con capucha ajustable y bolsillo frontal.\"\n",
    "price": "450",
    "category": "HOMBRE",
    "type": "Sudaderas",
    "theme": "Cine",
    "hasSizes": true,
    "specialLabel": "Ninguna",
    "id": 5,
    "imageType": "FRENTE Y REVERSA",
    "frenteImage": "https://i.postimg.cc/tJskBMpR/CARRIE_1.jpg",
    "reversaImage": "https://i.postimg.cc/T1K0t4fp/CARRIE_2.jpg"
  },
  {
    "name": "\"Carrie\" – Edición Terror Clásico",
    "description": "\"Sudadera premium en color negro profundo con diseño gráfico de la icónica película de Stephen King. Presenta el rostro de Carrie White en un contraste de alto impacto visual, capturando la esencia del suspenso y el cine de culto. Una prenda cómoda y duradera para fanáticos del género horror.\n\nDiseño: Estampado de gran detalle con enfoque en el dramatismo visual.\n\nEstilo: Cine de Terror / Culto.\n\nAjuste: Corte cómodo con capucha ajustable y bolsillo frontal.\"\n",
    "price": "450",
    "category": "MUJER",
    "type": "Sudaderas",
    "theme": "cine",
    "hasSizes": true,
    "specialLabel": "Ninguna",
    "id": 6,
    "imageType": "FRENTE Y REVERSA",
    "frenteImage": "https://i.postimg.cc/tJskBMpR/CARRIE_1.jpg",
    "reversaImage": "https://i.postimg.cc/T1K0t4fp/CARRIE_2.jpg"
  },
  {
    "name": "\"The 400 Blows\" (Los 400 Golpes)",
    "description": "\"Sudadera premium en color negro que celebra una de las obras maestras de la Nouvelle Vague. Presenta el icónico cuadro de Antoine Doinel en un diseño de alto contraste, ideal para cinéfilos que buscan una prenda con un mensaje visual profundo y artístico.\n\nDiseño: Estampado de alta definición con acabado tipo fotografía de época.\n\nEstilo: Cine de Autor / Culto.\n\nAjuste: Confortable con capucha ajustable y bolsillo frontal tipo canguro.\"\n",
    "price": "450",
    "category": "HOMBRE",
    "type": "Sudaderas",
    "theme": "CINE",
    "hasSizes": true,
    "specialLabel": "Ninguna",
    "id": 7,
    "imageType": "SÓLO FRENTE",
    "frenteImage": "https://i.postimg.cc/2ygwM7SS/the_400_blow_sudaderqa.jpg",
    "reversaImage": ""
  },
  {
    "name": "\"The 400 Blows\" (Los 400 Golpes)",
    "description": "\"Sudadera premium en color negro que celebra una de las obras maestras de la Nouvelle Vague. Presenta el icónico cuadro de Antoine Doinel en un diseño de alto contraste, ideal para cinéfilos que buscan una prenda con un mensaje visual profundo y artístico.\n\nDiseño: Estampado de alta definición con acabado tipo fotografía de época.\n\nEstilo: Cine de Autor / Culto.\n\nAjuste: Confortable con capucha ajustable y bolsillo frontal tipo canguro.\"\n",
    "price": "450",
    "category": "MUJER",
    "type": "Sudaderas",
    "theme": "CINE",
    "hasSizes": true,
    "specialLabel": "Ninguna",
    "id": 8,
    "imageType": "SÓLO FRENTE",
    "frenteImage": "https://i.postimg.cc/2ygwM7SS/the_400_blow_sudaderqa.jpg",
    "reversaImage": ""
  },
  {
    "name": "\"The 400 Blows\" The Beach ",
    "description": "\"Sudadera premium que rinde homenaje a la obra maestra de François Truffaut. Presenta el icónico cuadro final de Antoine Doinel en un diseño de alto contraste, ideal para coleccionistas que buscan una prenda con estética cinematográfica profunda y artística.\n\nDiseño: Impresión de alta definición con acabado fotográfico en blanco y negro.\n\nEstilo: Cine de Autor / Nouvelle Vague.\"\n",
    "price": "450",
    "category": "HOMBRE",
    "type": "Sudaderas",
    "theme": "cine",
    "hasSizes": true,
    "specialLabel": "Ninguna",
    "id": 9,
    "imageType": "SÓLO REVERSA",
    "frenteImage": "",
    "reversaImage": "https://i.postimg.cc/MHgDNmpT/the_400_blow_suadera_caminando_playa.jpg"
  },
  {
    "name": "\"The 400 Blows\" The Beach ",
    "description": "\"Sudadera premium que rinde homenaje a la obra maestra de François Truffaut. Presenta el icónico cuadro final de Antoine Doinel en un diseño de alto contraste, ideal para coleccionistas que buscan una prenda con estética cinematográfica profunda y artística.\n\nDiseño: Impresión de alta definición con acabado fotográfico en blanco y negro.\n\nEstilo: Cine de Autor / Nouvelle Vague.\"\n",
    "price": "450",
    "category": "MUJER",
    "type": "Sudaderas",
    "theme": "cine",
    "imageType": "SÓLO REVERSA",
    "frenteImage": "",
    "reversaImage": "https://i.postimg.cc/MHgDNmpT/the_400_blow_suadera_caminando_playa.jpg",
    "hasSizes": true,
    "specialLabel": "Ninguna",
    "id": 10
  },
  {
    "name": "\"María Félix\" – Edición Glamour & Ice Cream",
    "description": "\"Playera premium que muestra una faceta única y relajada de \"\"La Doña\"\". Un diseño que combina la elegancia indiscutible de María Félix con un toque pop y cotidiano, ideal para quienes buscan una prenda con personalidad, historia y un estilo visual refrescante.\n\nDiseño: Estampado de alta fidelidad con excelente contraste y detalle fotográfico.\n\nEstilo: Cine Mexicano / Cultura Pop / Vintage.\n\nCorte: Cuello redondo reforzado y algodón suave para uso diario.\"\n",
    "price": "150",
    "category": "MUJER",
    "type": "playera",
    "theme": "Cine Mexicano",
    "imageType": "SÓLO FRENTE",
    "frenteImage": "https://i.postimg.cc/ZnWHwM4v/maria_felix_helado.jpg",
    "reversaImage": "",
    "hasSizes": true,
    "specialLabel": "Ninguna",
    "id": 11
  },
  {
    "name": "Tote Bag  ny herald tribune",
    "description": "bolsa de lona premium un accesorio funcional que destaca por su diseño iconico de la prensa neoyorquina. Estilo minimalista que destaca por su tipografia clasica en contraste negro con fondo blanco  de alto impacto, \nDiseño: Estampado de alta fidelidad con excelente contraste y detalle.\n\nEstilo: Vintage.\n\nCualidad: Lona de algodón resistente, ideal para llevar libros, compras o esenciales diarios.\n",
    "price": "120",
    "category": "ACCESORIOS",
    "type": "Tote Bag",
    "theme": "Vintage ",
    "imageType": "SÓLO FRENTE",
    "frenteImage": "https://i.postimg.cc/7hjVdnZh/Whats_App_Image_2026_03_20_at_7_42_48_AM.jpg",
    "reversaImage": "",
    "hasSizes": false,
    "specialLabel": "Ninguna",
    "id": 12
  },
  {
    "name": "\"Pedro Infante\" – Época de Oro",
    "description": "\"Playera premium en color blanco que rinde homenaje al máximo ídolo de México. Presenta un retrato fotográfico clásico de Pedro Infante con su icónica sonrisa y carisma, capturando la esencia del \"\"Inmortal\"\". Una prenda indispensable para llevar la historia del cine mexicano con orgullo y estilo.\n\nDiseño: Impresión fotográfica de alta nitidez en contraste negro sobre blanco.\n\nEstilo: Cine de Oro Mexicano / Vintage / Icono Cultural.\n\nCorte: Cuello redondo con tejido de algodón suave y duradero.\"\n",
    "price": "150",
    "category": "HOMBRE",
    "type": "Playera",
    "theme": "Cine Mexicano",
    "imageType": "SÓLO FRENTE",
    "frenteImage": "https://i.postimg.cc/kGLczvgn/pedro_infante_playera.jpg",
    "reversaImage": "",
    "hasSizes": true,
    "specialLabel": "Ninguna",
    "id": 13
  },
  {
    "name": "\"Pedro Infante\" – Época de Oro",
    "description": "\"Playera premium en color blanco que rinde homenaje al máximo ídolo de México. Presenta un retrato fotográfico clásico de Pedro Infante con su icónica sonrisa y carisma, capturando la esencia del \"\"Inmortal\"\". Una prenda indispensable para llevar la historia del cine mexicano con orgullo y estilo.\n\nDiseño: Impresión fotográfica de alta nitidez en contraste negro sobre blanco.\n\nEstilo: Cine de Oro Mexicano / Vintage / Icono Cultural.\n\nCorte: Cuello redondo con tejido de algodón suave y duradero.\"\n",
    "price": "150",
    "category": "MUJER",
    "type": "playera",
    "theme": "Cine Mexicano",
    "imageType": "SÓLO FRENTE",
    "frenteImage": "https://i.postimg.cc/kGLczvgn/pedro_infante_playera.jpg",
    "reversaImage": "",
    "hasSizes": true,
    "specialLabel": "Ninguna",
    "id": 14
  },
  {
    "name": "Playera Blanca BTS – Edición \"México Tour\"",
    "description": "\"Playera premium que conmemora el paso de la agrupación más grande del K-Pop por tierras mexicanas. Presenta el logotipo oficial de BTS en un vibrante diseño que integra los colores y la energía de México. Una prenda de colección indispensable para cualquier ARMY que quiera llevar un recuerdo icónico de la banda con un toque local y auténtico.\n\nDiseño: Estampado de alta durabilidad con colores vivos and tipografía nítida.\n\nEstilo: K-Pop / Fan Edition / Streetwear.\n\nCorte: Cuello redondo reforzado and algodón suave de alta calidad para máximo confort.\"\n",
    "price": "150",
    "category": "MUJER",
    "type": "playera",
    "theme": "bts",
    "imageType": "SÓLO FRENTE",
    "frenteImage": "https://i.postimg.cc/L5JDxb29/bts_playera.jpg",
    "reversaImage": "",
    "hasSizes": true,
    "specialLabel": "Ninguna",
    "id": 15
  },
  {
    "name": "Playera Roja BTS – Edición \"México Tour\"",
    "description": "\"Playera premium que conmemora el paso de la agrupación más grande del K-Pop por tierras mexicanas. Presenta el logotipo oficial de BTS en un vibrante diseño que integra los colores y la energía de México. Una prenda de colección indispensable para cualquier ARMY que quiera llevar un recuerdo icónico de la banda con un toque local y auténtico.\n\nDiseño: Estampado de alta durabilidad con colores vivos and tipografía nítida.\n\nEstilo: K-Pop / Fan Edition / Streetwear.\n\nCorte: Cuello redondo reforzado and algodón suave de alta calidad para máximo confort.\"\n",
    "price": "150",
    "category": "MUJER",
    "type": "playera",
    "theme": "BTS",
    "imageType": "SÓLO FRENTE",
    "frenteImage": "https://i.postimg.cc/4NyZTpsq/bts_playera_ROJA.png",
    "reversaImage": "",
    "hasSizes": true,
    "specialLabel": "Ninguna",
    "id": 16
  },
  {
    "name": "\"Jorge Negrete\" – Leyenda del Cine de Oro",
    "description": "\"Playera premium que celebra la elegancia y la voz del gran Jorge Negrete. El diseño presenta un retrato clásico del \"\"Charro Cantor\"\", capturando la distinción y el porte que lo convirtieron en un icono de la cultura mexicana. Una prenda con carácter, ideal para quienes aprecian las raíces del cine y la música nacional.\n\nDiseño: Impresión de alta nitidez con excelente detalle en sombras y contrastes.\n\nEstilo: Cine de Oro Mexicano / Tradición / Vintage.\n\nCorte: Cuello redondo con tejido de algodón suave, de alta durabilidad y frescura.\"\n",
    "price": "150",
    "category": "MUJER",
    "type": "Playera",
    "theme": "Cine Mexicano",
    "imageType": "SÓLO FRENTE",
    "frenteImage": "https://i.postimg.cc/XqrLsz4r/Jorge_Negrete.jpg",
    "reversaImage": "",
    "hasSizes": true,
    "specialLabel": "Ninguna",
    "id": 17
  },
  {
    "name": "\"Three Colors: Red\" (Trois couleurs: Rouge)",
    "description": "\"Playera premium que rinde homenaje a la obra maestra final de Krzysztof Kieślowski. El diseño captura la esencia de la película con un enfoque minimalista y el uso simbólico del color rojo, representando la fraternidad y el destino en el cine europeo. Una prenda esencial para quienes buscan un estilo con profundidad artística y visual.\n\nDiseño: Estampado de alta fidelidad con énfasis en el contraste cromático y tipografía original.\n\nEstilo: Cine de Autor / Minimalista / Culto.\n\nCorte: Cuello redondo con tejido de algodón suave, diseñado para mantener la intensidad del color y la forma.\"\n",
    "price": "150",
    "category": "MUJER",
    "type": "PLAYERA",
    "theme": "CINE",
    "imageType": "SÓLO FRENTE",
    "frenteImage": "https://i.postimg.cc/MHgDNmp6/pelicula_francesa_tres_colores_rolo.jpg",
    "reversaImage": "",
    "hasSizes": true,
    "specialLabel": "Ninguna",
    "id": 18
  }
];

export const INITIAL_DELETED_ORDERS = [
  {
    "name": "rene",
    "city": "5630300021",
    "deliveryType": "Entrega personal",
    "items": [
      {
        "id": 2,
        "name": "Sudadera 'Stark' Industries",
        "price": "$195",
        "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=1974&auto=format&fit=crop",
        "size": "M",
        "quantity": 1
      }
    ],
    "total": 195,
    "id": "f6nxonbee",
    "date": "2026-03-26T05:01:18.855Z",
    "status": "En Preparación",
    "paymentMethod": "Tarjeta",
    "notes": [
      {
        "id": "1vhpsjtkt",
        "text": "El cliente quedo en decirnos la talla   estamos dando seguimietno todavi pendiente sigueretazado ",
        "date": "2026-03-26T15:25:12.344Z"
      }
    ]
  },
  {
    "name": "r",
    "city": "mexico ",
    "deliveryType": "Envío a domicilio",
    "items": [
      {
        "id": 1,
        "name": "Hoodie 'Gryffindor' Tech",
        "price": "$185",
        "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=1974&auto=format&fit=crop",
        "size": "M",
        "quantity": 1
      }
    ],
    "total": 185,
    "id": "vima7lfdk",
    "date": "2026-03-26T16:39:48.219Z",
    "status": "Pendiente",
    "paymentMethod": "Transferencia",
    "notes": []
  }
];
